spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t9Rio1Ehe385qLTnhQc
      secret-key: lLcHtvWyxb5ihM6ENIg0KuyvQhEtzs
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
server:
  port: 12000

    
