spring:
  cloud:
    gateway:
      routes:
        - id: test_router
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_router
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: lb://gmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


## 前端项目，/api
## 商品服务，/api/product
## Request URL: http://localhost:88/api/captcha.jpg http://renren-fast:8080/api/cartcha.jpg