spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.144.251:3306/gmall_pms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t9Rio1Ehe385qLTnhQc
      secret-key: lLcHtvWyxb5ihM6ENIg0KuyvQhEtzs
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
  application:
      name: gmall-product
#指定日期时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #设置主键为自增
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10500
  error:
    include-binding-errors: always
    include-message: always
#设置日志级别
logging:
  level:
    com.xyxy.gmall: debug

# 设置校验错误信息
